package com.prodigy4440.model;
// Generated Aug 14, 2014 11:29:28 AM by Hibernate Tools 3.6.0



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private String surname;
     private String firstname;
     private String staffId;
     private char userType;
     private String userName;
     private String password;
     private String secuirityQuestion;
     private String secuirityAnswer;

    public Account() {
    }

	
    public Account(char userType) {
        this.userType = userType;
    }
    public Account(String surname, String firstname, String staffId, char userType, String userName, String password, String secuirityQuestion, String secuirityAnswer) {
       this.surname = surname;
       this.firstname = firstname;
       this.staffId = staffId;
       this.userType = userType;
       this.userName = userName;
       this.password = password;
       this.secuirityQuestion = secuirityQuestion;
       this.secuirityAnswer = secuirityAnswer;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public char getUserType() {
        return this.userType;
    }
    
    public void setUserType(char userType) {
        this.userType = userType;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSecuirityQuestion() {
        return this.secuirityQuestion;
    }
    
    public void setSecuirityQuestion(String secuirityQuestion) {
        this.secuirityQuestion = secuirityQuestion;
    }
    public String getSecuirityAnswer() {
        return this.secuirityAnswer;
    }
    
    public void setSecuirityAnswer(String secuirityAnswer) {
        this.secuirityAnswer = secuirityAnswer;
    }




}


