package com.prodigy4440.model;
// Generated Aug 13, 2014 10:48:16 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Entry generated by hbm2java
 */
public class Entry  implements java.io.Serializable {


     private Integer entryId;
     private String tag;
     private String plateNumber;
     private byte[] driverImage;
     private Character entryType;
     private String registrationNo;
     private Date timeIn;
     private String timeOut;

    public Entry() {
    }

    public Entry(String tag, String plateNumber, byte[] driverImage, Character entryType, String registrationNo, Date timeIn, String timeOut) {
       this.tag = tag;
       this.plateNumber = plateNumber;
       this.driverImage = driverImage;
       this.entryType = entryType;
       this.registrationNo = registrationNo;
       this.timeIn = timeIn;
       this.timeOut = timeOut;
    }
   
    public Integer getEntryId() {
        return this.entryId;
    }
    
    public void setEntryId(Integer entryId) {
        this.entryId = entryId;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public String getPlateNumber() {
        return this.plateNumber;
    }
    
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }
    public byte[] getDriverImage() {
        return this.driverImage;
    }
    
    public void setDriverImage(byte[] driverImage) {
        this.driverImage = driverImage;
    }
    public Character getEntryType() {
        return this.entryType;
    }
    
    public void setEntryType(Character entryType) {
        this.entryType = entryType;
    }
    public String getRegistrationNo() {
        return this.registrationNo;
    }
    
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }
    public Date getTimeIn() {
        return this.timeIn;
    }
    
    public void setTimeIn(Date timeIn) {
        this.timeIn = timeIn;
    }
    public String getTimeOut() {
        return this.timeOut;
    }
    
    public void setTimeOut(String timeOut) {
        this.timeOut = timeOut;
    }

}


