package com.prodigy4440.model;
// Generated Aug 14, 2014 11:29:28 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Registration generated by hbm2java
 */
public class Registration  implements java.io.Serializable {


     private Integer registrationId;
     private String driverSurname;
     private String driverLastName;
     private String driverOccupation;
     private Character driverSex;
     private Integer driverAge;
     private String driverAddress;
     private String driverDisabilities;
     private String driverNationality;
     private String driverPhoneNumber;
     private byte[] driverPassport;
     private String licenseId;
     private String licenseName;
     private Date licenseExpiryDate;
     private String vehicleMake;
     private String vehicleModel;
     private String vehicleColor;
     private String vehiclePlateNumber;
     private String vehicleVin;
     private String registrationNo;

    public Registration() {
    }

    public Registration(String driverSurname, String driverLastName, String driverOccupation, Character driverSex, Integer driverAge, String driverAddress, String driverDisabilities, String driverNationality, String driverPhoneNumber, byte[] driverPassport, String licenseId, String licenseName, Date licenseExpiryDate, String vehicleMake, String vehicleModel, String vehicleColor, String vehiclePlateNumber, String vehicleVin, String registrationNo) {
       this.driverSurname = driverSurname;
       this.driverLastName = driverLastName;
       this.driverOccupation = driverOccupation;
       this.driverSex = driverSex;
       this.driverAge = driverAge;
       this.driverAddress = driverAddress;
       this.driverDisabilities = driverDisabilities;
       this.driverNationality = driverNationality;
       this.driverPhoneNumber = driverPhoneNumber;
       this.driverPassport = driverPassport;
       this.licenseId = licenseId;
       this.licenseName = licenseName;
       this.licenseExpiryDate = licenseExpiryDate;
       this.vehicleMake = vehicleMake;
       this.vehicleModel = vehicleModel;
       this.vehicleColor = vehicleColor;
       this.vehiclePlateNumber = vehiclePlateNumber;
       this.vehicleVin = vehicleVin;
       this.registrationNo = registrationNo;
    }
   
    public Integer getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(Integer registrationId) {
        this.registrationId = registrationId;
    }
    public String getDriverSurname() {
        return this.driverSurname;
    }
    
    public void setDriverSurname(String driverSurname) {
        this.driverSurname = driverSurname;
    }
    public String getDriverLastName() {
        return this.driverLastName;
    }
    
    public void setDriverLastName(String driverLastName) {
        this.driverLastName = driverLastName;
    }
    public String getDriverOccupation() {
        return this.driverOccupation;
    }
    
    public void setDriverOccupation(String driverOccupation) {
        this.driverOccupation = driverOccupation;
    }
    public Character getDriverSex() {
        return this.driverSex;
    }
    
    public void setDriverSex(Character driverSex) {
        this.driverSex = driverSex;
    }
    public Integer getDriverAge() {
        return this.driverAge;
    }
    
    public void setDriverAge(Integer driverAge) {
        this.driverAge = driverAge;
    }
    public String getDriverAddress() {
        return this.driverAddress;
    }
    
    public void setDriverAddress(String driverAddress) {
        this.driverAddress = driverAddress;
    }
    public String getDriverDisabilities() {
        return this.driverDisabilities;
    }
    
    public void setDriverDisabilities(String driverDisabilities) {
        this.driverDisabilities = driverDisabilities;
    }
    public String getDriverNationality() {
        return this.driverNationality;
    }
    
    public void setDriverNationality(String driverNationality) {
        this.driverNationality = driverNationality;
    }
    public String getDriverPhoneNumber() {
        return this.driverPhoneNumber;
    }
    
    public void setDriverPhoneNumber(String driverPhoneNumber) {
        this.driverPhoneNumber = driverPhoneNumber;
    }
    public byte[] getDriverPassport() {
        return this.driverPassport;
    }
    
    public void setDriverPassport(byte[] driverPassport) {
        this.driverPassport = driverPassport;
    }
    public String getLicenseId() {
        return this.licenseId;
    }
    
    public void setLicenseId(String licenseId) {
        this.licenseId = licenseId;
    }
    public String getLicenseName() {
        return this.licenseName;
    }
    
    public void setLicenseName(String licenseName) {
        this.licenseName = licenseName;
    }
    public Date getLicenseExpiryDate() {
        return this.licenseExpiryDate;
    }
    
    public void setLicenseExpiryDate(Date licenseExpiryDate) {
        this.licenseExpiryDate = licenseExpiryDate;
    }
    public String getVehicleMake() {
        return this.vehicleMake;
    }
    
    public void setVehicleMake(String vehicleMake) {
        this.vehicleMake = vehicleMake;
    }
    public String getVehicleModel() {
        return this.vehicleModel;
    }
    
    public void setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel;
    }
    public String getVehicleColor() {
        return this.vehicleColor;
    }
    
    public void setVehicleColor(String vehicleColor) {
        this.vehicleColor = vehicleColor;
    }
    public String getVehiclePlateNumber() {
        return this.vehiclePlateNumber;
    }
    
    public void setVehiclePlateNumber(String vehiclePlateNumber) {
        this.vehiclePlateNumber = vehiclePlateNumber;
    }
    public String getVehicleVin() {
        return this.vehicleVin;
    }
    
    public void setVehicleVin(String vehicleVin) {
        this.vehicleVin = vehicleVin;
    }
    public String getRegistrationNo() {
        return this.registrationNo;
    }
    
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }




}


